version: "3.7"

services:
  email-signature-dev:
    image: node:14-alpine
    container_name: email-signature-dev-0
    working_dir: /app
    volumes:
      - ./:/app
      - type: volume
        source: email-signature_node-modules
        target: /app/node_modules
    ports: 
      - 3000:3000
    networks: 
      - email-signature
    command: [ "sh", "-c", "npm install --prefer-offline --no-audit && npm start" ]
    tty: true

volumes:
  email-signature_node-modules:
    name: email-signature_node-modules

networks:
  email-signature:
    name: email-signature
